# Images are build from https://github.com/apache/rocketmq-docker
version: '3'
services:
  #Service for nameserver
  nameserver:
    image: apacherocketmq/rocketmq:4.9.2-alpine
    container_name: nameserver
    ports:
      - 9876:9876
    volumes:
      - ./data/nameserver/logs:/home/rocketmq/logs
    command: sh mqnamesrv

  broker:
    image: apacherocketmq/rocketmq:4.9.2-alpine
    container_name: broker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    environment:
      - NAMESRV_ADDR=namesrv:9876
    volumes:
      - ./data/broker/logs:/home/rocketmq/logs
      - ./data/broker/store:/home/rocketmq/store
      - ./data/broker/conf/broker.conf:/opt/rocketmq-4.9.2/conf/broker.conf
    command: sh mqbroker -c /opt/rocketmq-4.9.2/conf/broker.conf

  dashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: dashboard
    ports:
      - 8000:8080
    environment:
      - "JAVA_OPTS=-Drocketmq.namesrv.addr=nameserver:9876"
