
version: "3"
services:

  apt-cache:
    image: apt-cache
    container_name: apt-cache
    volumes:
      - "./cache:/var/cache/apt-cacher-ng"
    ports:
      - 3142:3142
    environment:
      - "http_proxy=http://host.docker.internal:1082"
      - "https_proxy=http://host.docker.internal:1082"


