version: "3.1"

services:
  seata-server:
    image: seata/seata-server:1.5.1
    build:
      context: seata-server
    container_name: seata-server
    ports:
      - "8091:8091"
      - "7091:7091"
    volumes:
      - "./application.yml:/seata-server/conf/application.yml"
    environment:
      - SEATA_PORT=8091
      - STORE_MODE=file
    expose:
      - 8091