version: "3.8"
services:

  # If want to use higher version of mysql, it is recommened to use mariadb 
  mysql-0:
    platform: linux/amd64   # for M1 Mac
    image: mysql:5.7
    container_name: mysql-0
    volumes:
      - "./mysql-0/data:/var/lib/mysql"
      - "./mysql-0/log:/var/log/mysql"
      - "./mysql-0/conf:/etc/mysql/conf.d"
      - "./mysql-0/init:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db
      MYSQL_USER: geniusv
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
