version: "3.8"
services:
  mysql:
    image: mysql:8.0.21
    container_name: mysql
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/log:/var/log/mysql"
      - "./mysql/conf:/etc/mysql/conf.d"
      - "./mysql/init:/docker-entrypoint-initdb.d"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db
      MYSQL_USER: geniusv
      MYSQL_PASSWORD: 123456
    ports:
      - "3306"
