version: "3.7"
services:
  zk-0:
    image: zookeeper:3.7.0
    restart: always
    container_name: zk-0
    hostname: zk-0
    ports:
      - 2180:2181
    volumes:
#      - "./zookeeper/conf:/conf"
      - "./zookeeper/zk-0/data:/data"
      - "./zookeeper/zk-0/datalog:/datalog"
    environment:
      ZOO_MY_ID: 0
      ZOO_SERVERS: server.0=zk-0:2888:3888;2181

  kafka-0:
    image: wurstmeister/kafka:2.13-2.7.0
    restart: unless-stopped
    container_name: kafka-0
    ports:
      - "9090:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_HOST_NAME: 192.168.2.127                   # need to change: host machine IP
      KAFKA_ADVERTISED_PORT: 9090                                 # need to change: host machine mapping port
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.2.127:9090    # 绑定发布订阅的端口。修改:宿主机IP
      KAFKA_ZOOKEEPER_CONNECT: "zk-0:2181"
    volumes:
      - "./kafka/kafka-0/docker.sock:/var/run/docker.sock"
      - "./kafka/kafka-0/data/:/kafka"
#networks: 
#  app-network:
#    ipam:
#      config:
#        - subnet: 172.16.0.0/24