version: "3"
services:
  redis-0:
    image: redis:6.0.7
    container_name: redis-0
    volumes:
      - "./redis-0/data:/data"
      - "./redis-0/config:/usr/local/etc/redis/"
    ports:
      - 6000:6379
    command: "redis-server /usr/local/etc/redis/redis.conf"
